config/routes.rb
Oea::Application.routes.draw do
  root :to => "default#index"

  devise_for :users

  resources :users do
    resources :assessments, except: [:update, :edit], :controller => "assessments"
  end

  resources :assessments
  resources :assessment_loaders
  resources :assessment_results
  resources :item_results

  get 'saml', to: 'saml#index'
  get 'saml/metadata', to: 'saml#metadata'
  post 'saml/consume', to: 'saml#consume'

  # oembed
  match 'oembed' => 'oembed#endpoint', :via => [:get, :post]

  namespace :api do
    resources :assessments
    resources :assessment_results
    resources :item_results
  end

  match '/proxy' => 'default#proxy', via: [:get, :post]
  match '/contact' => 'default#contact', via: [:get, :post]
  match '/about' => 'default#about', via: [:get]
  match '/take' => 'default#take', via: [:get]
end

app/models/assessment.rb
class Assessment < ActiveRecord::Base
  validates_presence_of :title

  acts_as_taggable_on :keywords

  has_many :sections, dependent: :destroy
  has_many :items, through: :sections
  has_many :assessment_results, dependent: :destroy
  belongs_to :user
  has_many :assessment_xmls, dependent: :destroy
  has_many :assessment_outcomes
  has_many :outcomes, through: :assessment_outcomes

  scope :by_newest, -> { order(created_at: :desc) }
  scope :by_oldest, -> { order(start_date: :asc) }
  scope :by_latest, -> { order(updated_at: :desc) }

  def self.from_xml(input_xml, user, src_url=nil, published_at=nil, file_name = nil)
    if xml = AssessmentParser.parse(input_xml).first || ItemParser.parse(input_xml).first
      assessment = Assessment.find_by(identifier: xml.ident, user_id: user.id) || user.assessments.build
      assessment.identifier = xml.ident
      assessment.title = xml.title
    else
      assessment = Assessment.find_by(identifier: file_name, user_id: user.id) || user.assessments.build
      assessment.identifier = file_name
      assessment.title = File.basename(file_name)
    end
    assessment.description = 'Assessment'
    assessment.src_url = src_url
    assessment.published_at = published_at
    assessment.save!

    assessment.assessment_xmls.create!(:xml => input_xml)

    if xml && xml.respond_to?(:sections)
      assessment.create_subitems(xml)
    end

    assessment
  end

  def create_subitems(xml)
    xml.sections.collect do |section_xml|
      Section.from_xml(section_xml, self)
    end
  end

  def raw_results( scope_url = nil )
    results = scope_url ? assessment_results.where("referer LIKE ?", "%#{scope_url}%") : assessment_results
  end

  def results_summary( scope_url = nil )
    @results_summary ||= begin
      users = []
      referers = []

      results = raw_results( scope_url )

      results.map do |assessment_result|
        users << assessment_result.user if !users.include?(assessment_result.user)
        referers << assessment_result.referer if !assessment_result.referer.nil? && !referers.include?(item_result.referer)
      end

      submitted = results.by_status_final.load

      {
        renders: users.count,
        submitted: submitted,
        users: users,
        referers: referers,
      }
    end
  end

end

app/controllers/api/assessments_controller.rb
class Api::AssessmentsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_filter :authenticate_user_from_token!, only: [:create]
  before_filter :skip_trackable
  before_filter :authenticate_user!, only: [:create]
  respond_to :xml, :json

  def index
    page = (params[:page] || 1).to_i
    per_page = 100
    @assessments = Assessment.all
    if params[:q].present?
      q = "%#{params[:q]}%"
      @assessments = @assessments.where("title ILIKE ? OR description ILIKE ?", q, q).paginate(:page => page, :per_page => per_page)
    end
    respond_to do |format|
      format.json { render :json => @assessments }
      format.xml { render }
    end
  end

  def show
    assessment = Assessment.find(params[:id])
    respond_to do |format|
      format.json { render :json => assessment }
      format.xml { render :text => assessment.assessment_xmls.by_newest.first.xml }
    end
  end

  def create
    assessment = Assessment.from_xml(request.body.read, current_user)
    respond_with(:api, assessment)
  end

end

app/controllers/assessments_controller.rb
require 'open-uri'

class AssessmentsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_filter :skip_trackable
  before_filter :authenticate_user!, only: [:new, :create, :destroy]
  load_and_authorize_resource except: [:index, :show, :create]

  respond_to :html

  def index
    if params[:user_id].present?
      @assessments = User.find(params[:user_id]).assessments
    else
      @assessments = Assessment.all
    end
  end

  def show
    if params[:load_ui] == 'true'
      @embedded = false
    else
      @embedded = params[:src_url].present? || params[:embed].present?
    end
    @confidence_levels = params[:confidence_levels] ? true : false
    @enable_start = params[:enable_start] ? true : false
    @eid = params[:eid] if params[:eid]
    @keywords = params[:keywords] if params[:keywords]
    @external_user_id = params[:external_user_id] if params[:external_user_id]
    @results_end_point = ensure_scheme(params[:results_end_point]) if params[:results_end_point].present?
    if params[:id].present? && !['load', 'offline'].include?(params[:id])
      @assessment = Assessment.find(params[:id])
      @eid ||= @assessment.identifier
      if @embedded
        # Just show the assessment. This is here to support old style embed with id=# and embed=true
        @src_url = embed_url(@assessment)
      else
        # Show the full page with analtyics and embed code buttons
        @embed_code = embed_code(@assessment, @confidence_levels, @eid, @enable_start, params[:offline].present?)
      end
    else
      # Get the remote url where we can download the qti
      @src_url = ensure_scheme(URI.decode(params[:src_url])) if params[:src_url].present?
      if params[:load_ui] == 'true'
        # Build an embed code and stats page for an assessment loaded via a url
        @embed_code = embed_code(nil, @confidence_levels, @eid, @enable_start, params[:offline].present?, params[:src_url])
      end
    end

    @assessment_id = @assessment ? @assessment.id : params[:assessment_id] || 'null'

    if params[:offline].present? && @src_url.present?
      @src_data = open(@src_url).read
      xml = EdxSequentialParser.parse(@src_data)
      # edX
      if defined?(xml.verticals)
        base_uri = @src_url[0, @src_url.index('sequential')];
        @edx_verticals = crawlEdx(base_uri, 'vertical', xml.verticals.map(&:url_name))
        @edx_problems = {}
        @edx_verticals.each do |id, vertical|
          xml = EdxVerticalParser.parse(vertical)
          @edx_problems.merge!(crawlEdx(base_uri, 'problem', xml.problems.map(&:url_name)))
        end
      end
    end

    respond_to do |format|
      format.html { render :layout => @embedded ? 'bare' : 'application' }
    end
  end

  def new
  end

  def create
    xml = assessment_params[:xml_file].read
    @assessment = Assessment.from_xml(xml, current_user)
    @assessment.title = assessment_params[:title] if assessment_params[:title].present?
    @assessment.description = assessment_params[:description] if assessment_params[:description].present?
    @assessment.license = assessment_params[:license] if assessment_params[:license].present?
    @assessment.keyword_list.add(assessment_params[:keywords], parse: true) if assessment_params[:keywords].present?
    @assessment.save!
    respond_with(@assessment)
  end

  def destroy
    @assessment.destroy
    respond_to do |format|
      format.html { redirect_to(user_assessments_url(current_user)) }
    end
  end

  private

    def crawlEdx(base_uri, type, ids)
      ids.inject({}) do |hsh, id|
        hsh[id] = open(base_uri + type + '/' + id + '.xml').read
        hsh
      end
    end

    def assessment_params
      params.require(:assessment).permit(:title, :description, :xml_file, :license, :keywords)
    end

end

app/views/assessments/_assessment.html.erb
<div class="section_list">
  <div class="section_container">
    <%= render partial: 'items/item', object: @item, locals: {display_embed_code: display_embed_code, display_nav: display_nav, next_item: @next_item, prev_item: @prev_item, assessment: assessment, current_index: @current_index+1, question_count: @question_count} %>
  </div>
</div>

app/views/assessments/_edx_data.html.erb
<% edx_data.each do |id, xml| -%>
<script id="<%=id%>" type="text/x-data">
  <%= xml %>
</script>
<% end %>

app/views/assessments/_list_item.html.erb
<li>
  <%= link_to assessment.title, assessment_path(assessment.id) %>
  <span class="action_links">
    <%= link_to '<i class="glyphicon glyphicon-signal"></i>'.html_safe, assessment_result_path(assessment) %>
    <%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, assessment_path(assessment), :method => :delete %>
  </span>
</li>

app/views/assessments/index.html.erb
<div class="container">

  <div class="assessment_list well row">
    <h2>Load Assessment By Url</h2>

    <%= form_tag(assessment_loaders_path, html: { :role => 'form' }) do -%>
      <div class="form-group">
        <%= label_tag "assessment", "Enter the web address of a QTI or EdX format assessment" %>
        <%= text_field_tag :src_url, nil, class: "form-control", id: "assessment_src_url" %>
        <p class="help-block">(e.g. <%= "http://#{request.host_with_port}/assessment.xml" %>)</p>
      </div>

      <div class="form-group">
        <%= label_tag "assessment", "Enter the embed identifier" %>
        <%= text_field_tag :eid, nil, class: "form-control", id: "assessment_eid" %>
        <p class="help-block">(We generate one for you based on the assessment url, but you can change it to any value you like)</p>
      </div>

      <div class="form-group">
        <%= label_tag "keywords", "Keywords" %>
        <%= text_field_tag :keywords, nil, class: "form-control" %>
        <p class="help-block">
          (Optional. Keywords will be stored along with student responses and be used 
          later on to search for specific results.)
        </p>
      </div>

      <div class="form-group">
        <%= label_tag "external_user_id", "External User Id" %>
        <%= text_field_tag :external_user_id, nil, class: "form-control" %>
        <p class="help-block">
          (Optional. Provide an identifier for a user that can be used to query results for that user later on.)
        </p>
      </div>

      <div class="form-group">
        <%= label_tag "style", "Select style" %>
        <%= select_tag "style", options_for_select(available_styles), class: "form-control" %>
        <p class="help-block">(OEA is the default style.)</p>
      </div>

      <div class="form-group">
        <%= check_box_tag :confidence_levels, 'true', true %>
        <%= label_tag "confidence_levels", "Display confidence controls" %>
      </div>
      
      <%= submit_tag "View Assessment", :class => "btn" %>
    <% end -%>
  </div>

  <div class="assessment_list well row">
    <h2>Assessments</h2>
    <ul>
      <%= render :collection => @assessments, :partial => 'assessments/list_item', :as => :assessment %>
    </ul>
    <%= link_to "<i class='icon-plus'></i> Create an Assessment".html_safe, new_assessment_path, :class => 'nav_link'  %>
  </div>

</div>

app/views/assessments/new.html.erb
<div id="assessments" class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <h1 class="row"><%= link_to 'Assessments', user_assessments_path(current_user.id) %> &gt; Create an Assessment</h1>
      <%= render :partial => 'layouts/global/errors', locals: { obj: @assessment } %>
      <div class="well row">
        <%= form_for :assessment, :url => assessments_path, :html => { role: 'form' } do |f| -%>
          <h2>Steps to create an assessment:</h2>
          <ol>
            <li>Author the assessment using a Learning Management System like <a target="_blank" href="https://canvas.instructure.com">Canvas</a>.</li>
            <li>Create an assessment file by exporting the assessment to disk in <a target="_blank" href="http://en.wikipedia.org/wiki/QTI">QTI format</a>.</li>
            <li>Import the assessment file here.</li>
          </ol>

          <div class="form-group">
            <%= f.label :title, "Assessment Title", :class => "control-label" %>
            <%= f.text_field :title, :class => "form-control" %>
            <p class="help-block">This value is optional. If left blank OEA will attempt to use the title of the assessment from the QTI file.</p>
          </div>

          <div class="form-group">
            <%= f.label :keywords, "Assessment Keywords", :class => "control-label" %>
            <%= f.text_field :keywords, :class => "form-control" %>
            <p class="help-block">This value is optional.</p>
          </div>

          <div class="form-group">
            <%= f.label :description, "Description", :class => "control-label" %>
            <%= f.text_area :description, :class => "form-control" %>
            <p class="help-block">This value is optional.</p>
          </div>

          <div class="form-group">
            <%= f.label :license, "License", :class => "control-label" %>
            <%= f.text_area :license, :class => "form-control" %>
            <p class="help-block">This value is optional.</p>
          </div>

          <div class="form-group">
            <%= f.label :xml_file, "Select QTI file to upload", :class => "control-label" %>
            <%= f.file_field :xml_file %>
          </div>

          <%= f.submit 'Upload', :class => 'btn' %>
        <% end -%>

      </div>
    </div>
  </div>
</div>

app/views/assessments/show.html.erb
<% if @embed_code.present? -%>
  <div class="container">
    <h1><%= link_to 'Assessments', assessments_path %> &gt; <%= @assessment.present? ? @assessment.title : @eid || @src_url %></h1>
    <div class="assessment">
      <%= @embed_code.html_safe %>
    </div>
    <div class="assessment_meta">
      <div class="assessment_buttons">
        <p><span class="stats_word">stats</span><a href="<%= assessment_result_path(params[:assessment_id] || @assessment || 0, eid: params[:eid]) %>" class="btn btn-info stats_button" target="_top"><i class="glyphicon glyphicon-signal"></i></a></p>
        <p><span class="embed_word">embed</span><a href="#" class="btn btn-info embed_button">&lt/&gt</a></p>
      </div>
      <form class="embed_code">
        <div class="form-group">
          <%= label_tag "embed_text", "Embed Code:" %>
          <textarea class="embed_text" name="embed_text"> <%= @embed_code %></textarea>
        </div>
        <div class="form-group">
          <%= check_box_tag :confidence_levels, 'true', true %>
          <%= label_tag "confidence_levels", "Display confidence controls" %>
        </div>
        <div class="form-group">
          <%= check_box_tag :resize_script, 'true', true %>
          <%= label_tag "resize_script", "Include resize script" %>
        </div>
      </form>
    </div>
  </div>
<% else -%>
  <script>
    window.ENV = {"rootURL":"/assessments/load","FEATURES":{}};
  </script>
  <script id="srcData" type="text/x-data">
    <%= @src_data %>
  </script>

  <%= render(partial: 'assessments/edx_data', object: @edx_verticals) if @edx_verticals.present? -%>
  <%= render(partial: 'assessments/edx_data', object: @edx_problems) if @edx_problems.present? -%>

  <script type="text/javascript">
    window.OEA_SETTINGS = {
      srcUrl: '<%= @src_url %>',
      style: '<%= params[:style] %>',
      assessmentId: <%= @assessment_id %>,
      <% if @external_user_id %>
      externalUserId: <%= @external_user_id  %>,
      <% end %>
      <% if @keywords %>
      keywords: '<%= @keywords %>',
      <% end %>
      resultsEndPoint: '<%= @results_end_point || "http://#{request.host_with_port}/api" %>',
      confidenceLevels: <%= @confidence_levels %>,
      enableStart: <%= @enable_start %>,
      <% if @eid %>
      eId: '<%= @eid %>',
      <% end %>
      offline: <%= @src_data.present? %>
    };
  </script>
  <%= javascript_include_tag "oea/application" %>
<% end -%>

<%= javascript_include_tag "openassessments.js" %>