config/routes.rb
Oea::Application.routes.draw do
  root :to => "default#index"

  devise_for :users

  resources :users do
    resources :assessments, except: [:update, :edit], :controller => "assessments"
  end

  resources :assessments
  resources :assessment_loaders
  resources :assessment_results
  resources :item_results

  get 'saml', to: 'saml#index'
  get 'saml/metadata', to: 'saml#metadata'
  post 'saml/consume', to: 'saml#consume'

  # oembed
  match 'oembed' => 'oembed#endpoint', :via => [:get, :post]

  namespace :api do
    resources :assessments
    resources :assessment_results
    resources :item_results
  end

  match '/proxy' => 'default#proxy', via: [:get, :post]
  match '/contact' => 'default#contact', via: [:get, :post]
  match '/about' => 'default#about', via: [:get]
  match '/take' => 'default#take', via: [:get]
end

app/models/item_result.rb
class ItemResult < ActiveRecord::Base
  belongs_to :item
  belongs_to :user
  belongs_to :assessment_result

  acts_as_taggable_on :keywords
  acts_as_taggable_on :objectives

  before_save :validate_session_status

  scope :by_status_final, -> { where(session_status: 'final') }

  STATUS_INITIAL = 'initial'
  STATUS_PENDING_SUBMISSION = 'pendingSubmission'
  STATUS_PENDING_RESPONSE_PROCESSING  = 'pendingResponseProcessing'
  STATUS_FINAL = 'final'

  STATUS_VALUES = [STATUS_INITIAL, STATUS_PENDING_SUBMISSION, STATUS_PENDING_RESPONSE_PROCESSING, STATUS_FINAL]

  def validate_session_status
    if !STATUS_VALUES.include?(self.session_status)
      raise "Not a valid session status."
    end
  end

  def item_variable=(hash)
    write_attribute(:item_variable, hash.to_json)
  end

  def item_variable
    JSON.parse(read_attribute(:item_variable)) rescue nil
  end

  def self.raw_results( opts={} )
    results = []
    if opts[:scope_url].present?
      results = ItemResult.where("referer LIKE ?", "%#{opts[:scope_url]}%")
    end

    if opts[:identifier].present?
      results.concat ItemResult.where(identifier: opts[:identifier])
    end

    if opts[:eid].present?
      results.concat ItemResult.where(eid: opts[:eid])
    end

    if opts[:keyword].present?
      results.concat ItemResult.tagged_with(opts[:keyword])
    end

    if opts[:objective].present?
      results.concat ItemResult.tagged_with(opts[:objective])
    end

    if opts[:external_user_id].present?
      results.concat ItemResult.where(external_user_id: opts[:external_user_id])
    end

    if opts[:src_url].present?
      results.concat ItemResult.where(src_url: opts[:src_url])
    end

    results

  end

  def self.results_summary(results)

    users = []
    referers = []
    correct = []
    submitted = []
    time_elapsed = []
    confidence_level = []
    identifiers = {}

    results.each do |item_result|
      identifiers[item_result.identifier] ||= []
      identifiers[item_result.identifier] << item_result
      users << item_result.user if !users.include?(item_result.user)
      referers << item_result.referer if !item_result.referer.nil? && !referers.include?(item_result.referer)
      correct << item_result if item_result.correct
      time_elapsed << item_result.time_elapsed
      confidence_level << item_result.confidence_level
    end

    results.each do |result|
      if result.session_status == 'final'
        submitted << result
      end
    end

    item_summaries = []
    identifiers.each do |identifier, item_results|
      
      final_submissions = item_results.find_all{|ir| ir.session_status == 'final'}
      number_submitted = final_submissions.count
      total_correct = final_submissions.find_all{|ir| ir.correct}.count

      item_summaries << {
        identifier: identifier,
        number_renders: item_results.length,
        number_submitted: number_submitted,
        percent_correct: number_submitted > 0 ? (total_correct.to_f/number_submitted.to_f) * 100 : 0,
        number_referers: item_results.map(&:referer).uniq.count,
        number_of_users: item_results.map(&:user_id).uniq.count
      }
    end
    {
      identifiers: identifiers,
      item_summaries: item_summaries,
      renders: users.count,
      submitted: submitted,
      users: users,
      referers: referers,
      correct: correct,
      percent_correct: submitted.count > 0 ? correct.count.to_f / submitted.count.to_f : 0,
      time_elapsed: average_of(time_elapsed) || 0,
      confidence_level: average_of(confidence_level) || 'none'
    }
  end

  def self.average_of(arr)
    return 0 if arr.blank?
    arr.inject(0.0) { |sum, el| sum + (el || 0) } / arr.size
  end

end

app/controllers/api/item_results_controller.rb
class Api::ItemResultsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_filter :skip_trackable
  respond_to :json, :csv, :xml

  def index
    scope_url = params[:url]
    scope_url = get_domain(scope_url) if params[:scope] == 'domain'
    identifier = params[:identifier] if params[:identifier]
    eid = params[:eid] if params[:eid]
    keyword = params[:keyword] if params[:keyword]
    external_user_id = params[:external_user_id] if params[:external_user_id]
    src_url = params[:src_url] if params[:src_url]
    objective = params[:objective] if params[:objective]
    results = ItemResult.raw_results( scope_url: scope_url, identifier: identifier, eid: eid, keyword: keyword, objective: objective, external_user_id: external_user_id, src_url: src_url )
    if params[:type] == 'summary'
      results = ItemResult.results_summary(results)
    end
    respond_to do |format|
      format.json { render json: results }
      format.xml { render xml: results }
      format.csv { render text: results.to_csv }
    end
  end

  def create
    rendered_time, referer, user = tracking_info
    item_result = user.item_results.create!(
      identifier: params[:identifier],
      item_id: params[:item_id],
      src_url: params[:src_url],
      external_user_id: params[:external_user_id],
      assessment_result_id: params[:assessment_result_id],
      eid: params[:eid],
      rendered_datestamp: rendered_time,
      referer: referer,
      ip_address: request.ip,
      time_elapsed: params['time_elapsed'],
      confidence_level: convert_confidence_level,
      correct: params[:correct],
      score: params[:score],
      session_status: params[:session_status] || 'initial')
    item_result.keyword_list.add(params[:keywords], parse: true) if params[:keywords]
    item_result.objective_list.add(params[:objectives], parse: true) if params[:objectives]
    item_result.save! if params[:objectives] || params[:keywords]
    respond_with(:api, item_result)
  end

  private

  def convert_confidence_level
    case params['confidence_level']
      when "Maybe?" then 1
      when "Probably." then 2
      when "Definitely!" then 3
    end
  end

end

app/controllers/item_results_controller.rb
class ItemResultsController < ApplicationController

  def index
    
    @title = [ params[:scope_url],
      params[:identifier],
      params[:eid],
      params[:keyword],
      params[:objective],
      params[:external_user_id],
      params[:src_url]].reject! { |i| i.blank? }.join(' and ')

    @item_results = ItemResult.raw_results(params)

    if @summary = params[:type] == 'summary'
      summaries = ItemResult.results_summary(@item_results)
      @item_results_summary = summaries[:item_summaries][0]
      @avg_time_to_complete = summaries[:time_elapsed]/60
      @avg_confidence = summaries[:confidence_level]
    end

    respond_to do |format|
      format.html do
        render
      end
      format.json do
        if params[:type] == 'summary'
          render json: ItemResult.results_summary(@item_results)
        else
          render json: @item_results
        end
      end
      format.csv {
        filename = @title.gsub(/[^0-9A-Za-z.\-]/, '_').truncate(30)
        if params[:type] == 'summary'
          send_data(
            results_summary_csv,
            :type => "text/csv",
            :filename =>  "results_summary_#{filename}.csv",
            :disposition => "attachment"
          )
        else
          send_data(
            results_csv,
            :type => "text/csv",
            :filename =>  "results_#{filename}.csv",
            :disposition => "attachment"
          )
        end
     }
    end
  end

  private
    def results_summary_csv
      CSV.generate do |csv|
        csv << ["Number of Times Displayed", "Number of Unique Users", "Number of Submissions", "Average Score", "Number of Referers", "Average Time Spent Completing Assessment (seconds)", "Average Confidence"]
        csv << [@item_results_summary[:number_renders], @item_results_summary[:number_of_users], @item_results_summary[:number_submitted], signif(@item_results_summary[:percent_correct], 2) , @item_results_summary[:number_referers], @avg_time_to_complete, @avg_confidence]
      end
    end

    def results_csv
      CSV.generate do |csv|
        csv << ItemResult.column_names
        @item_results.each do |result|
          csv << result.attributes.values_at(*ItemResult.column_names)
        end
      end
    end

end

app/views/item_results/_item_result.html.erb
<tr>
  <td><%= item_result.identifier %></td>
  <td><%= item_result.sequence_index %></td>
  <td><%= item_result.datestamp.nil? ? 'Not submitted.' : item_result.datestamp.strftime("%B %d, %Y @ %l:%M%p") %></td>
  <td><%= item_result.session_status.titleize %></td>
  <td><%= item_result.item_variable %></td>
  <td><%= item_result.candidate_comment %></td>
  <td><%= item_result.rendered_datestamp.strftime("%B %d, %Y @ %l:%M:%S%p") %></td>
  <td><%= item_result.referer %></td>
  <td><%= item_result.ip_address %></td>
  <td><%= item_result.item_id %></td>
  <td><%= item_result.user_id %></td>
  <td><%= item_result.created_at %></td>
  <td><%= item_result.updated_at %></td>
  <td><%= item_result.assessment_result_id %></td>
  <td><%= item_result.time_elapsed %></td>
  <td><%= item_result.confidence_level %></td>
  <td><%= item_result.eid %></td>
  <td><%= item_result.src_url %></td>
  <td><%= item_result.external_user_id %></td>
  <td><%= item_result.keyword_list %></td>
  <td><%= item_result.objective_list %></td>
  <td><%= item_result.correct %></td>
  <td><%= item_result.score %></td>
</tr>

app/views/item_results/_summary.html.erb
<tr>
  <td>
    <%= summary[:identifier] %>
  </td>
  <td>
    <%= summary[:number_renders] %>
  </td>
  <td>
    <%= summary[:number_submitted] %>
  </td>
  <td>
    <%= signif(summary[:percent_correct], 2) %>%
  </td>
  <td>
    <%= summary[:number_referers] %>
  </td>
  <td>
    <%= summary[:number_of_users] %>
  </td>
  <td>
    <a href="<%= item_results_url(summary[:identifier], format: :csv, type: "summary") %>">
      <i class='glyphicon glyphicon-download'></i>
    </a>
  </td>
</tr>

app/views/item_results/index.html.erb
<% content_for :page_title do -%>
  Item Results for <%= @title %>
<% end -%>

<% if @summary -%>
<div class="results_container">
  <div class="container">
    <div class="row">
      <div class="col-sm-10 col-sm-offset-1">
        <div class="well">
          <h2>Item Results for <%= @item_results_summary[:identifier] %> <small class="pull-right"><%= link_to 'Raw Results', item_results_path(identifier: @item_results_summary[:identifier]) %></small></h2>
          <table class="table">
            <tbody>
              <tr>
                <th>Number of Times Displayed</th>
                <td><%= @item_results_summary[:number_renders] %></td>
              </tr>
              <tr>
                <th>Number of Unique Users</th>
                <td><%= @item_results_summary[:number_of_users] %></td>
              </tr>
              <tr>
                <th>Number of Submissions</th>
                <td><%= @item_results_summary[:number_submitted] %></td>
              </tr>
              <tr>
                <th>Average Score</th>
                <td><%= signif(@item_results_summary[:percent_correct], 2) %>%</td>
              </tr>
              <tr>
                <th>Number of Referers</th>
                <td><%= @item_results_summary[:number_referers] %></td>
              </tr>
              <tr>
                <th>Average Time Spent Completing Assessment</th>
                <td><%= distance_of_time_in_words( @avg_time_to_complete ) %></td>
              </tr>
              <tr>
                <th>Average Confidence</th>
                <td><%= @avg_confidence %></td>
              </tr>
              <tr>
                <th>CSV Download</th>
                <td><a href="<%= item_results_path(identifier: @item_results_summary[:identifier], format: :csv, type: "summary") %>"><i class="glyphicon glyphicon-download"></i></a></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<% else -%>
  <div class="item_results_table">
    <h2>
      Item Results for <%= @title %> 
      <small class="pull-right"><%= link_to 'Summary', item_results_path(params.merge(type: :summary)) %></small>
    </h2>
    <h2>
      <a href="<%= item_results_path(params.merge(format: :csv)) %>">
        <small><i class='glyphicon glyphicon-download'></i> CSV</small>
      </a>
    </h2>
    <table class="table table-striped table-bordered" id="item_results">
      <thead>
        <tr>
          <th>Identifier</th>
          <th>Sequence Index</th>
          <th>Datestamp</th>
          <th>Session Status</th>
          <th>Item Variable</th>
          <th>Candidate Comment</th>
          <th>Rendered Datestamp</th>
          <th>Referer</th>
          <th>Ip Address</th>
          <th>Item Id</th>
          <th>User Id</th>
          <th>Created At</th>
          <th>Updated At</th>
          <th>Assessment Result Id</th>
          <th>Time Elapsed</th>
          <th>Confidence Level</th>
          <th>Eid</th>
          <th>Src Url</th>
          <th>External User Id</th>
          <th>Keywords</th>
          <th>Objectives</th>
          <th>Correct</th>
          <th>Score</th>
        </tr>
      </thead>
      <tbody>
        <%= render @item_results %>
      </tbody>
    </table>
  </div>
<% end -%>