config/routes.rb
Oea::Application.routes.draw do
  root :to => "default#index"

  devise_for :users

  resources :users do
    resources :assessments, except: [:update, :edit], :controller => "assessments"
  end

  resources :assessments
  resources :assessment_loaders
  resources :assessment_results
  resources :item_results

  get 'saml', to: 'saml#index'
  get 'saml/metadata', to: 'saml#metadata'
  post 'saml/consume', to: 'saml#consume'

  # oembed
  match 'oembed' => 'oembed#endpoint', :via => [:get, :post]

  namespace :api do
    resources :assessments
    resources :assessment_results
    resources :item_results
  end

  match '/proxy' => 'default#proxy', via: [:get, :post]
  match '/contact' => 'default#contact', via: [:get, :post]
  match '/about' => 'default#about', via: [:get]
  match '/take' => 'default#take', via: [:get]
end

app/models/assessment_result.rb
class AssessmentResult < ActiveRecord::Base
  has_one :test_result, dependent: :destroy
  belongs_to :assessment
  has_many :item_results, dependent: :destroy

  acts_as_taggable_on :keywords
  acts_as_taggable_on :objectives

  scope :by_status_final, -> { where(session_status: 'final') }

  STATUS_INITIAL = 'initial'
  STATUS_PENDING_SUBMISSION = 'pendingSubmission'
  STATUS_PENDING_RESPONSE_PROCESSING  = 'pendingResponseProcessing'
  STATUS_FINAL = 'final'

  STATUS_VALUES = [STATUS_INITIAL, STATUS_PENDING_SUBMISSION, STATUS_PENDING_RESPONSE_PROCESSING, STATUS_FINAL]

end

app/controllers/api/assessment_results_controller.rb
class Api::AssessmentResultsController < ApplicationController

  skip_before_filter :verify_authenticity_token
  before_filter :skip_trackable
  respond_to :json

  # TODO Might have to cheat and make this a index or show so we can use a GET request to record the data. This will avoid cross origin issues.
  def create
    rendered_time, referer, user = tracking_info
    assessment_result = user.assessment_results.create!(
      assessment_id: params[:assessment_id],
      eid: params[:eid],
      src_url: params[:src_url],
      external_user_id: params[:external_user_id],
      identifier: params['identifier'],
      rendered_datestamp: rendered_time,
      referer: referer,
      ip_address: request.ip,
      session_status: 'initial')

    assessment_result.keyword_list.add(params[:keywords], parse: true) if params[:keywords]
    assessment_result.objective_list.add(params[:objectives], parse: true) if params[:objectives]
    assessment_result.save! if params[:objectives] || params[:keywords]
    respond_with(:api, assessment_result)
  end

end

app/controllers/assessment_results_controller.rb
class AssessmentResultsController < ApplicationController

  def show

    if params[:id].present? && params[:id].to_i > 0
      # The assessment lives in OEA
      @assessment = Assessment.find(params[:id])
      @assessment_results = AssessmentResult.where(assessment_id: @assessment.id) 
    else
      # The assessment does not live in OEA
      @assessment_query = query(:identifier) || query(:eid) || query(:src_url)
      render nothing: true, status: :not_acceptable and return if @assessment_query.blank?
      @assessment_results = AssessmentResult.where(@assessment_query)  
    end

    @item_results = ItemResult.where(assessment_result_id: @assessment_results.map(&:id))

    respond_to do |format|
      format.html do
        @displayed = @assessment_results.length
        @unique_users_count = @assessment_results.uniq.pluck(:user_id).count
        @submissions_count = @item_results.where(session_status: 'final').count
        results_summaries = ItemResult.results_summary(@item_results)
        @percent_correct = signif(results_summaries[:percent_correct] * 100, 2) #reject zeros?
        @avg_time_to_complete = results_summaries[:time_elapsed]/60
        @avg_confidence = results_summaries[:confidence_level]
        @item_summaries = results_summaries[:item_summaries]
      end
      format.json do
        render json: @item_results
      end
      format.csv do
        identifier = @assessment.id.to_s if @assessment.present?
        identifier ||= params[:identifier] || params[:eid] || params[:src_url]
        identifier.gsub!(/[^0-9A-Za-z.\-]/, '_')
        send_data(
          csv_result(@item_results),
          :type => "text/csv",
          :filename => "assessment_results_#{identifier}.csv",
          :disposition => "attachment"
        )
      end
    end
  end

  private

    def query(key)
      {key => params[key]} if params[key].present?
    end

    def csv_result(item_results)
      CSV.generate do |csv|
        csv << ItemResult.column_names
        item_results.each do |result|
          csv << result.attributes.values_at(*ItemResult.column_names)
        end
      end
    end

end

app/helpers/assessment_results_helper.rb
module AssessmentResultsHelper

  def assessment_result_title
    if @assessment
      link_to @assessment.title, assessment_path(@assessment)
    elsif params[:src_url].present?
      link_to params[:src_url], params[:src_url]
    else
      params[:identifier] || params[:eid]
    end
  end

end

app/views/assessment_results/_summary.html.erb
<tr>
  <td>
    <%= link_to summary[:identifier],  item_results_url(identifier: summary[:identifier], type: 'summary') %>
  </td>
  <td>
    <%= summary[:number_renders] %>
  </td>
  <td>
    <%= summary[:number_submitted] %>
  </td>
  <td>
    <%= signif(summary[:percent_correct], 2) %>%
  </td>
  <td>
    <%= summary[:number_referers] %>
  </td>
  <td>
    <%= summary[:number_of_users] %>
  </td>
  <td>
    <a href="<%= item_results_url(identifier: summary[:identifier], format: 'csv') %>">
      <i class='glyphicon glyphicon-download'></i>
    </a>
  </td>
</tr>

app/views/assessment_results/index.html.erb
<div class="container">
  <div class="row">

    <div class="col-sm-8 col-sm-offset-2">

      <h1 class="row">
        <% if current_user -%><%= link_to 'Assessments', user_assessments_path(current_user.id) %> &gt;<% end -%>
        <%= link_to @assessment.title, assessment_path(@assessment) %>  &gt; Results
      </h1>

      <div class="well row">
        <h2>Assessment Results<h2>
        <table class="table" id='assessment_results'>
          <tbody>
            <tr>
              <th>Number of Times Displayed</th>
              <td><%= @displayed %></td>
            </tr>
            <tr>
              <th>Number of Unique Users</th>
              <td><%= @unique_users_count %></td>
            </tr>
            <tr>
              <th>Number of Submissions</th>
              <td><%= @submissions_count %></td>
            </tr>
            <tr>
              <th>Average Score</th>
              <td><%= @percent_correct %>%</td>
            </tr>
            <tr>
              <th>Average Time Spent Completing Assessment</th>
              <td><%= distance_of_time_in_words( @avg_time_to_complete ) %></td>
            </tr>
            <tr>
              <th>CSV Download</th>
              <td><a href="<%= results_assessment_url(params[:assessment_id] || @assessment, :format => :csv, :type => "summary") %>"><i class='icon-download'></i></a></td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="well row">
        <h2>Item Results<h2>
          <table class="table" id='item_results'>
            <thead>
            <tr>
              <th>
              Item
            </th>
              <th>
                # Renders
              </th>
              <th>
                # Submitted
              </th>
              <th>
                % Correct
              </th>
              <th>
                # Of Referers
              </th>
              <th>
                # Of Users
              </th>
              <th>
                CSV
              </th>
              </tr>
            </thead>
          <tbody>
        <%= render :collection => @assessment.items, :partial => 'item_results/summary', as: :item, locals:{ assessment: @assessment }  %>
          </tbody>
        </table>
      </div>

    </div>
  </div>

</div>

app/views/assessment_results/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-sm-10 col-sm-offset-1">

      <h1 class="row">
        <% if current_user -%><%= link_to 'Assessments', user_assessments_path(current_user.id) %> &gt;<% end -%>
        <%= assessment_result_title %> &gt; Results
      </h1>

      <div class="well row">
        <h2>Assessment Results<h2>
        <table class="table" id='assessment_results'>
          <tbody>
            <tr>
              <th>Number of Times Displayed</th>
              <td><%= @displayed %></td>
            </tr>
            <tr>
              <th>Number of Unique Users</th>
              <td><%= @unique_users_count %></td>
            </tr>
            <tr>
              <th>Number of Submissions</th>
              <td><%= @submissions_count %></td>
            </tr>
            <tr>
              <th>Average Score</th>
              <td><%= @percent_correct %>%</td>
            </tr>
            <tr>
              <th>Average Time Spent Completing Assessment</th>
              <td><%= distance_of_time_in_words( @avg_time_to_complete ) %></td>
            </tr>
            <tr>
              <th>Average Confidence</th>
              <td><%= @avg_confidence %></td>
            </tr>
            <tr>
              <th>CSV Download</th>
              <td><a href="<%= assessment_result_url(@assessment || 0, @assessment_query, format: :csv, type: "summary") %>"><i class="glyphicon glyphicon-download"></i></a></td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="well row">
        <h2>Item Results<h2>
          <table class="table" id="item_results">
            <thead>
            <tr>
              <th>
              Item
            </th>
              <th>
                # Renders
              </th>
              <th>
                # Submitted
              </th>
              <th>
                % Correct
              </th>
              <th>
                # Of Referers
              </th>
              <th>
                # Of Users
              </th>
              <th>
                CSV
              </th>
              </tr>
            </thead>
          <tbody>
            <%= render collection: @item_summaries, partial: 'summary' %>
          </tbody>
        </table>
      </div>

    </div>
  </div>

</div>