config/routes.rb
Oea::Application.routes.draw do
  root :to => "default#index"

  devise_for :users

  resources :users do
    resources :assessments, except: [:update, :edit], :controller => "assessments"
  end

  resources :assessments
  resources :assessment_loaders
  resources :assessment_results
  resources :item_results

  get 'saml', to: 'saml#index'
  get 'saml/metadata', to: 'saml#metadata'
  post 'saml/consume', to: 'saml#consume'

  # oembed
  match 'oembed' => 'oembed#endpoint', :via => [:get, :post]

  namespace :api do
    resources :assessments
    resources :assessment_results
    resources :item_results
  end

  match '/proxy' => 'default#proxy', via: [:get, :post]
  match '/contact' => 'default#contact', via: [:get, :post]
  match '/about' => 'default#about', via: [:get]
  match '/take' => 'default#take', via: [:get]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render 'layouts/global/head' %>
  <%= stylesheet_link_tag "application", media: "all" %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to image_tag(image_path("logo.png"), :class => 'logo', :alt => 'Open Assessments'), '/' -%>
        <%= link_to image_tag(image_path("#{yield(:logo_overlay).presence ? yield(:logo_overlay).presence.strip : 'home'}.png"), :class => 'logo_overlay'), '/' -%>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li class="<%= 'active' if current_page?(root_path) %>"><a href="/">HOME</a></li>
          <li class="<%= 'active' if current_page?(assessments_path) %>"><a href="<%=assessments_path%>">ASSESSMENTS</a></li>
          <li class="<%= 'active' if current_page?(contact_path) %>" ><a href="/contact">CONTACT</a></li>
          <li><a href="https://github.com/tatemae/oea/wiki/API-Documentation" target="_blank">API</a></li>
          <li><a href="https://github.com/tatemae/oea" target="_blank">THE CODE</a></li>
          <li class="<%= 'active' if current_page?(about_path) %>" ><a href="/about">ABOUT</a></li>
          <% if user_signed_in? %>
            <li>
              <%= link_to current_user.display_name, user_assessments_path(current_user), :style => 'padding-right:2px;float:left;' %>
              <%= link_to "(sign out)", destroy_user_session_path, :method => :delete, :style => 'font-size:14px;padding-left:2px;float:left;' %>
            </li>
          <% else %>
            <li class="<%= 'active' if current_page?('/users/sign_in') %>" ><%= link_to "SIGN IN", new_user_session_path %></li>
            <li class="<%= 'active' if current_page?('/users/sign_up') %>" ><%= link_to "SIGN UP", new_user_registration_path %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
  <%= render 'layouts/global/messages' %>
  <%= yield %>
  <footer>
    <p><i>Funded by</i> <%= link_to image_tag('mit.png', :alt => 'Massachusetts Institute of Technology OEIT'), 'http://oeit.mit.edu/about' %> <i>Built by</i> <%= link_to 'Atomic Jolt', 'http://www.atomicjolt.com/' %></p>
  </footer>
  <%= javascript_include_tag "application" %>
</body>
</html>

app/views/layouts/bare.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render 'layouts/global/head' %>
  <%= stylesheet_link_tag "bare", media: "all" %>
</head>
<body>
  <%= render 'layouts/global/messages' %>
  <%= yield %>
  <%= javascript_include_tag "application" %>
</body>
</html>